site_name: OWASP Security Champions Guide
site_description: OWASP Security Champions Guide
#repo_name: OWASP/SCG
#repo_url: https://github.com/OWASP/SCG
copyright: This work is licensed under a <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution Share Alike 4.0 International license</a>.
docs_dir: docs
theme:
  name: material
  language: en
  logo: assets/OWASP_Logo_Transp.png
  features:
    - navigation.sections

plugins:
  - search
  - blog:
      archive_date_format: MMMM yyyy
      categories_allowed:
        - Welcome
        - News
  - offline

nav:
  - Introduction: index.md
  #- Notice: '0x00-notice.md'
  #- Introduction: 'Introduction.md'
  - Manifesto: 'Manifesto.md'
  #- About OWASP: 'A00-about-owasp.md'
  - Principles:
    - 1. Be passionate about security: 'Be_passionate_about_security.md'
    - 2. Start with a clear vision for your program: 'Start_with_a_clear_vision_for_your_program.md'
    - 3. Secure management support: 'Secure_management_support.md'
    - 4. Nominate a dedicated captain: 'Nominate_a_dedicated_captain.md'
    - 5. Trust your champions: 'Trust_your_champions.md'
    - 6. Create a community: 'Create_a_community.md'
    - 7. Promote knowledge sharing: 'Promote_knowledge_sharing.md'
    - 8. Reward responsibility: 'Reward_responsibility.md'
    - 9. Invest in your champions: 'Invest_in_your_champions.md'
    - 10. Anticipate personnel changes: 'Anticipate_personnel_changes.md'
    - Maturity model: 'Maturity_model.md'
    - Get involved: 'Get_involved.md'
    - Blog: blog/index.md

markdown_extensions:
  - attr_list